This is makeindex, version 2.15 [MiKTeX 2.9.6930 64-bit] (kpathsea + Thai support).
Scanning style file ./index.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file index.acn....done (35 entries accepted, 0 rejected).
Sorting entries....done (180 comparisons).
Generating output file index.acr....done (54 lines written, 0 warnings).
Output written in index.acr.
Transcript written in index.alg.
